In [3]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import os

LINEAR REGRESSION


In [64]:
# Import numpy and SystemDS
import numpy as np
from systemds.context import SystemDSContext
from systemds.operator.algorithm import lm,lmPredict



# compute the weights
with SystemDSContext() as sds:
    
    data=pd.read_csv('Dataset/mitbih_train.csv')

    X = data.iloc[:, :-1].values
    y = data.iloc[:, -1].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

    weights = lm(sds.from_numpy(X_train), sds.from_numpy(y_train)).compute()
    print(weights)
    # generate predictions use lmPredict fuction
    predictions = lmPredict(sds.from_numpy(X_train),weights)

    

    
    
  




[[ 5.07138219e-01]
 [-1.20266283e+00]
 [ 4.93303274e-01]
 [ 7.97778086e-01]
 [ 5.25315300e-01]
 [ 5.01641990e-01]
 [ 1.36213211e+00]
 [-6.17520768e-01]
 [ 1.62398859e+00]
 [-3.68070810e-01]
 [-3.91254554e+00]
 [-2.72743467e+00]
 [ 7.77566309e-01]
 [-5.35639290e-01]
 [-1.75750681e+00]
 [-7.74399176e-01]
 [ 1.92851683e+00]
 [ 2.63051485e+00]
 [ 1.96202267e+00]
 [ 9.29475501e-01]
 [-1.22288608e+00]
 [-1.77724319e-01]
 [-1.12238647e+00]
 [-1.48878567e-01]
 [-9.51568324e-01]
 [ 7.97323238e-01]
 [ 4.56694128e-01]
 [ 8.84483728e-01]
 [ 1.75433189e-01]
 [ 2.15392805e-02]
 [-3.68671453e-01]
 [-5.61753005e-01]
 [-1.38369153e+00]
 [ 3.23767386e-01]
 [ 5.73305167e-01]
 [ 3.60767666e-01]
 [ 1.98961595e-02]
 [-1.22411462e-01]
 [ 1.81563689e-01]
 [ 6.24483989e-02]
 [ 1.37509924e-01]
 [ 2.57694037e-01]
 [-1.74009971e-03]
 [ 1.51442448e-02]
 [ 3.21181237e-01]
 [-2.42809949e-02]
 [ 2.80076700e-01]
 [ 3.32648186e-01]
 [-2.02840178e-01]
 [ 3.74101466e-01]
 [-5.84444564e-02]
 [ 2.35758307e-01]
 [ 5.5054019

In [12]:
import pandas as pd
data=pd.read_csv('Dataset/mitbih_train.csv')
# double the size of dataset by selecting random rows in it
data=data.append(data.sample(frac=1)) #1GB size
# data=data.append(data.sample(frac=1)) #2GB size
# data=data.append(data.sample(frac=1)) #4GB size
# print(data.shape)

MULTILOG REGRESSION


In [11]:
from systemds.context import SystemDSContext
from systemds.examples.tutorials.adult import DataManager
from systemds.operator.algorithm import multiLogReg
from systemds.operator.algorithm import multiLogRegPredict
from systemds.operator.algorithm import confusionMatrix
from sklearn.model_selection import train_test_split
import numpy as np


with SystemDSContext() as sds:
    d = DataManager()

    

    X = data.iloc[:, :-1].values
    y = data.iloc[:, -1].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6)

    # Train model
    betas = multiLogReg(sds.from_numpy(X_train), sds.from_numpy(y_train), verbose=False)

    # Apply model
    [_, y_pred, acc] = multiLogRegPredict(sds.from_numpy(X_test), betas, Y=sds.from_numpy(y_test))

    y_pred = y_pred.compute()

RuntimeError: 



An error occurred while calling z:org.apache.sysds.runtime.util.Py4jConverterUtils.convertPy4JArrayToMB. Trace:
java.lang.NegativeArraySizeException: -222519424
	at py4j.Base64.decode(Base64.java:321)
	at py4j.Protocol.getBytes(Protocol.java:178)
	at py4j.Protocol.getObject(Protocol.java:299)
	at py4j.commands.AbstractCommand.getArguments(AbstractCommand.java:82)
	at py4j.commands.CallCommand.execute(CallCommand.java:77)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)



In [6]:
# Import numpy and SystemDS
import numpy as np
from systemds.context import SystemDSContext
from systemds.operator.algorithm import lm

# Set a seed
np.random.seed(0)
# Generate matrix of feature vectors
features = np.random.rand(10, 15)
# Generate a 1-column matrix of response values
y = np.random.rand(10, 1)

# compute the weights
with SystemDSContext() as sds:
  weights = lm(sds.from_numpy(features), sds.from_numpy(y)).compute()
  print(weights)
  predictions = sds.from_numpy(features) * weights
  print(predictions)

[[-0.11538199]
 [-0.20386541]
 [-0.39956034]
 [ 1.04078623]
 [ 0.43270839]
 [ 0.18954599]
 [ 0.49858969]
 [-0.26812763]
 [ 0.09961844]
 [-0.57000751]
 [-0.43386048]
 [ 0.55358873]
 [-0.54638565]
 [ 0.2205885 ]
 [ 0.37957689]]
MatrixNode


In [25]:
import logging

import numpy as np
from systemds.context import SystemDSContext

# create a random array
m1 = np.array(np.random.randint(100, size=5 * 5) + 1.01, dtype=np.double)
m1.shape = (5, 5)
# create another random array
m2 = np.array(np.random.randint(5, size=5 * 5) + 1, dtype=np.double)
m2.shape = (5, 5)

# Create a context
with SystemDSContext() as sds:
    # element-wise matrix multiplication, note that nothing is executed yet!
    m_res = sds.from_numpy(m1) * sds.from_numpy(m2)
    # lets do the actual computation in SystemDS! The result is an numpy array
    m_res_np = m_res.compute()
    print(m_res_np)
  

[[276.04 116.04 372.04 182.02  48.01]
 [142.02 450.05 275.05 185.05  56.02]
 [360.04 212.04 290.05 295.05 265.05]
 [292.04  27.03  61.01  94.01  36.03]
 [176.04 192.02 144.03  28.02  95.05]]


In [27]:
import logging

from systemds.context import SystemDSContext
from systemds.operator.algorithm import l2svm

with SystemDSContext() as sds:
    # Generate 10 by 10 matrix with values in range 0 to 100.
    features = sds.rand(10, 10, 0, 100)
    # Add value to all cells in features
    features += 1.1
    # Generate labels of all ones and zeros
    labels = sds.rand(10, 1, 1, 1, sparsity=0.5)

    model = l2svm(features, labels, verbose=False).compute()
    print(model)

[[ 0.05309455]
 [-0.01856637]
 [-0.01564793]
 [-0.01246604]
 [ 0.00094563]
 [ 0.01936491]
 [-0.00512524]
 [ 0.01599459]
 [-0.02032598]
 [-0.02263818]]
